name: End-to-end tests
on:
  push:
    branches:
      - 'main'

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      # Checkout the repository
      - name: Checkout
        uses: actions/checkout@v4

      # Install npm dependencies and run all Cypress tests
    - name: Install npm dependencies and Cypress run
      uses: cypress-io/github-action@v6
      with:
    browser: chrome
    config-file: cypress.config.js

      # Copy test execution videos and screenshots
      - name: Copy test execution artifacts
        run: |
          mkdir public
          cp -r cypress/videos public/videos
          cp -r cypress/screenshots public/screenshots

      # Merge test reports
      - name: Merge test reports
        run: npm run combine:report

      # Generate HTML report
      - name: Generate HTML report
        run: npm run generate:report

      # Deploy report to GitHub Pages
      - name: Deploy report page to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
