name: End-to-end tests
on:
  push:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      # Checkout the repository
      - name: Checkout
        uses: actions/checkout@v4

      # Install npm dependencies and run all Cypress tests
      - name: Install npm dependencies and Cypress run
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          config-file: cypress.config.js

      # Deploy report to GitHub Pages
      - name: Deploy report page to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
